const now = Date.now()
const d = (days) => now - days * 86400000

const PROPERTIES = [
  {
    id: 'prop-001',
    address: 'Andrássy út 22., Budapest VI.',
    type: 'Lakás',
    plan: 'premium',
    status: 'active',
    rooms: 3,
    sqm: 85,
    price: '€299',
    visits: 214,
    chatbotQuestions: 47,
    createdAt: d(45),
    expiresAt: d(-15),
    embedUrl: 'https://tour.ingatlas.hu/andrassy-22',
  },
  {
    id: 'prop-002',
    address: 'Váci utca 10., Budapest V.',
    type: 'Iroda',
    plan: 'premium',
    status: 'active',
    rooms: 2,
    sqm: 120,
    price: '€299',
    visits: 189,
    chatbotQuestions: 63,
    createdAt: d(38),
    expiresAt: d(-22),
    embedUrl: 'https://tour.ingatlas.hu/vaci-10',
  },
  {
    id: 'prop-003',
    address: 'Margit körút 55., Budapest II.',
    type: 'Lakás',
    plan: 'basic',
    status: 'active',
    rooms: 2,
    sqm: 62,
    price: '€149',
    visits: 97,
    chatbotQuestions: 28,
    createdAt: d(30),
    expiresAt: d(-30),
    embedUrl: 'https://tour.ingatlas.hu/margit-55',
  },
  {
    id: 'prop-004',
    address: 'Király utca 34., Budapest VII.',
    type: 'Üzlet',
    plan: 'premium',
    status: 'expired',
    rooms: 1,
    sqm: 95,
    price: '€299',
    visits: 61,
    chatbotQuestions: 15,
    createdAt: d(90),
    expiresAt: d(30),
    embedUrl: null,
  },
  {
    id: 'prop-005',
    address: 'Bartók Béla út 78., Budapest XI.',
    type: 'Lakás',
    plan: 'premium',
    status: 'active',
    rooms: 4,
    sqm: 110,
    price: '€299',
    visits: 342,
    chatbotQuestions: 81,
    createdAt: d(14),
    expiresAt: d(-76),
    embedUrl: 'https://tour.ingatlas.hu/bartok-78',
  },
  {
    id: 'prop-006',
    address: 'Fő utca 12., Budaörs',
    type: 'Ház',
    plan: 'basic',
    status: 'processing',
    rooms: 5,
    sqm: 160,
    price: '€149',
    visits: 0,
    chatbotQuestions: 0,
    createdAt: d(2),
    expiresAt: d(-88),
    embedUrl: null,
  },
  {
    id: 'prop-007',
    address: 'Szent István körút 30., Budapest XIII.',
    type: 'Lakás',
    plan: 'premium',
    status: 'active',
    rooms: 3,
    sqm: 78,
    price: '€299',
    visits: 156,
    chatbotQuestions: 42,
    createdAt: d(25),
    expiresAt: d(-35),
    embedUrl: 'https://tour.ingatlas.hu/szentistvan-30',
  },
  {
    id: 'prop-008',
    address: 'Rákóczi út 45., Budapest VIII.',
    type: 'Üzlet',
    plan: 'basic',
    status: 'active',
    rooms: 1,
    sqm: 55,
    price: '€149',
    visits: 73,
    chatbotQuestions: 19,
    createdAt: d(20),
    expiresAt: d(-40),
    embedUrl: 'https://tour.ingatlas.hu/rakoczi-45',
  },
  {
    id: 'prop-009',
    address: 'Dózsa György út 88., Budapest XIV.',
    type: 'Iroda',
    plan: 'premium',
    status: 'active',
    rooms: 3,
    sqm: 200,
    price: '€299',
    visits: 201,
    chatbotQuestions: 55,
    createdAt: d(18),
    expiresAt: d(-42),
    embedUrl: 'https://tour.ingatlas.hu/dozsa-88',
  },
  {
    id: 'prop-010',
    address: 'Csaba utca 7., Budapest XII.',
    type: 'Ház',
    plan: 'premium',
    status: 'active',
    rooms: 6,
    sqm: 240,
    price: '€299',
    visits: 428,
    chatbotQuestions: 112,
    createdAt: d(10),
    expiresAt: d(-50),
    embedUrl: 'https://tour.ingatlas.hu/csaba-7',
  },
  {
    id: 'prop-011',
    address: 'Alkotás utca 15., Székesfehérvár',
    type: 'Lakás',
    plan: 'basic',
    status: 'active',
    rooms: 2,
    sqm: 58,
    price: '€149',
    visits: 44,
    chatbotQuestions: 12,
    createdAt: d(28),
    expiresAt: d(-32),
    embedUrl: 'https://tour.ingatlas.hu/alkotas-15',
  },
  {
    id: 'prop-012',
    address: 'Petőfi utca 3., Debrecen',
    type: 'Ház',
    plan: 'basic',
    status: 'expired',
    rooms: 4,
    sqm: 130,
    price: '€149',
    visits: 89,
    chatbotQuestions: 31,
    createdAt: d(95),
    expiresAt: d(35),
    embedUrl: null,
  },
]

const MONTHLY_VISITS = [
  { month: 'Jan', value: 312 },
  { month: 'Feb', value: 366 },
  { month: 'Már', value: 330 },
  { month: 'Ápr', value: 444 },
  { month: 'Máj', value: 408 },
  { month: 'Jún', value: 498 },
  { month: 'Júl', value: 462 },
  { month: 'Aug', value: 546 },
  { month: 'Szep', value: 516 },
  { month: 'Okt', value: 564 },
  { month: 'Nov', value: 528 },
  { month: 'Dec', value: 600 },
]

const DAILY_VISITS = Array.from({ length: 30 }, (_, i) => ({
  date: new Date(d(29 - i)).toISOString().slice(0, 10),
  value: Math.floor(Math.random() * 40) + 10,
})).sort((a, b) => a.date.localeCompare(b.date))

const CHATBOT_QUESTIONS = [
  { id: 1, property: 'Andrássy út 22.', question: 'Mekkora a belmagasság?', category: 'belmagasság', count: 12, date: d(3) },
  { id: 2, property: 'Andrássy út 22.', question: 'Milyen tájolású a nappali?', category: 'tájolás', count: 9, date: d(5) },
  { id: 3, property: 'Andrássy út 22.', question: 'Van a közelben parkolási lehetőség?', category: 'parkolás', count: 8, date: d(2) },
  { id: 4, property: 'Andrássy út 22.', question: 'Mennyi a közös költség?', category: 'költség', count: 7, date: d(1) },
  { id: 5, property: 'Váci utca 10.', question: 'Milyen a közlekedés a környéken?', category: 'közlekedés', count: 15, date: d(4) },
  { id: 6, property: 'Váci utca 10.', question: 'Mekkora az iroda alapterülete?', category: 'alapterület', count: 11, date: d(2) },
  { id: 7, property: 'Váci utca 10.', question: 'Van saját mosdó?', category: 'felszereltség', count: 10, date: d(6) },
  { id: 8, property: 'Bartók Béla út 78.', question: 'Mikor épült az épület?', category: 'épület', count: 14, date: d(1) },
  { id: 9, property: 'Bartók Béla út 78.', question: 'Van erkély vagy terasz?', category: 'felszereltség', count: 13, date: d(2) },
  { id: 10, property: 'Bartók Béla út 78.', question: 'Mennyi a rezsi átlagosan?', category: 'költség', count: 12, date: d(3) },
  { id: 11, property: 'Bartók Béla út 78.', question: 'Milyen iskolák vannak a közelben?', category: 'környék', count: 11, date: d(5) },
  { id: 12, property: 'Csaba utca 7.', question: 'Mekkora a telek?', category: 'alapterület', count: 18, date: d(1) },
  { id: 13, property: 'Csaba utca 7.', question: 'Van medence vagy kert?', category: 'felszereltség', count: 16, date: d(2) },
  { id: 14, property: 'Csaba utca 7.', question: 'Milyen a környék biztonsága?', category: 'környék', count: 14, date: d(3) },
  { id: 15, property: 'Csaba utca 7.', question: 'Gázfűtés vagy távfűtés?', category: 'felszereltség', count: 12, date: d(4) },
  { id: 16, property: 'Margit körút 55.', question: 'Van lift a házban?', category: 'felszereltség', count: 8, date: d(2) },
  { id: 17, property: 'Szent István körút 30.', question: 'Milyen boltok vannak a közelben?', category: 'környék', count: 10, date: d(3) },
  { id: 18, property: 'Dózsa György út 88.', question: 'Hány parkolóhely tartozik hozzá?', category: 'parkolás', count: 13, date: d(5) },
]

const CATEGORY_COUNTS = {
  belmagasság: 12,
  tájolás: 9,
  parkolás: 21,
  költség: 19,
  közlekedés: 15,
  alapterület: 29,
  felszereltség: 59,
  épület: 14,
  környék: 35,
}

const HEATMAP_DATA = [
  {
    propertyId: 'prop-005',
    property: 'Bartók Béla út 78.',
    rooms: [
      { name: 'Nappali', timePercent: 35, color: '#0a0a0a' },
      { name: 'Konyha', timePercent: 22, color: '#333' },
      { name: 'Hálószoba 1', timePercent: 18, color: '#555' },
      { name: 'Hálószoba 2', timePercent: 12, color: '#888' },
      { name: 'Fürdőszoba', timePercent: 8, color: '#bbb' },
      { name: 'Erkély', timePercent: 5, color: '#ddd' },
    ],
    totalViewTime: '18 perc',
    avgViewTime: '4 perc 30 mp',
  },
  {
    propertyId: 'prop-010',
    property: 'Csaba utca 7.',
    rooms: [
      { name: 'Nappali + étkező', timePercent: 28, color: '#0a0a0a' },
      { name: 'Kert', timePercent: 24, color: '#333' },
      { name: 'Konyha', timePercent: 18, color: '#555' },
      { name: 'Hálószoba 1', timePercent: 14, color: '#888' },
      { name: 'Hálószoba 2', timePercent: 8, color: '#bbb' },
      { name: 'Garázs', timePercent: 5, color: '#ccc' },
      { name: 'Fürdőszoba', timePercent: 3, color: '#ddd' },
    ],
    totalViewTime: '24 perc',
    avgViewTime: '6 perc 10 mp',
  },
  {
    propertyId: 'prop-001',
    property: 'Andrássy út 22.',
    rooms: [
      { name: 'Nappali', timePercent: 40, color: '#0a0a0a' },
      { name: 'Hálószoba', timePercent: 25, color: '#333' },
      { name: 'Konyha', timePercent: 20, color: '#555' },
      { name: 'Fürdőszoba', timePercent: 10, color: '#888' },
      { name: 'Előszoba', timePercent: 5, color: '#bbb' },
    ],
    totalViewTime: '12 perc',
    avgViewTime: '3 perc 20 mp',
  },
]

const SEO_TEXTS = [
  {
    id: 'seo-001',
    property: 'Andrássy út 22., Budapest VI.',
    status: 'published',
    title: 'Prémium lakás az Andrássy úton – 3 szoba, 85 m²',
    excerpt: 'Fényűző, 3 szobás lakás Budapest szívében, az Andrássy úton. Kiváló közlekedés, elegáns környék, 85 m²-es, teljesen felújított ingatlan.',
    createdAt: d(40),
  },
  {
    id: 'seo-002',
    property: 'Bartók Béla út 78., Budapest XI.',
    status: 'published',
    title: 'Tágas polgári lakás Újbudán – 4 szoba, 110 m², erkély',
    excerpt: '4 szobás, 110 m²-es polgári lakás a Bartók Béla úton. Erkély, magas belmagasság, kiváló infrastruktúra. Azonnal költözhető.',
    createdAt: d(10),
  },
  {
    id: 'seo-003',
    property: 'Csaba utca 7., Budapest XII.',
    status: 'published',
    title: 'Családi ház a Hegyvidéken – 6 szoba, 240 m², kert',
    excerpt: 'Hat szobás, 240 m²-es családi ház Budapest egyik legzöldebb kerületében. Gondozott kert, garázs, panoráma. Prémium kivitelezés.',
    createdAt: d(8),
  },
  {
    id: 'seo-004',
    property: 'Váci utca 10., Budapest V.',
    status: 'published',
    title: 'Reprezentatív iroda a Váci utcában – 120 m², azonnali',
    excerpt: '120 m²-es, prémium irodahelyiség a belváros szívében. Saját mosdó, recepció, tárgyaló. Kiváló tömegközlekedési kapcsolatok.',
    createdAt: d(35),
  },
  {
    id: 'seo-005',
    property: 'Dózsa György út 88., Budapest XIV.',
    status: 'draft',
    title: 'Modern iroda Zuglóban – 200 m², 3 szoba',
    excerpt: '',
    createdAt: d(15),
  },
  {
    id: 'seo-006',
    property: 'Szent István körút 30., Budapest XIII.',
    status: 'draft',
    title: 'Felújított lakás a Szent István körúton – 3 szoba',
    excerpt: '',
    createdAt: d(22),
  },
]

const TEAM_MEMBERS = [
  { id: 'user-001', name: 'Kovács Anna', email: 'anna.kovacs@ingatlas.hu', role: 'admin', avatar: 'AK', joined: d(365) },
  { id: 'user-002', name: 'Nagy Péter', email: 'peter.nagy@ingatlas.hu', role: 'manager', avatar: 'NP', joined: d(240) },
  { id: 'user-003', name: 'Szabó Márta', email: 'marta.szabo@ingatlas.hu', role: 'editor', avatar: 'SM', joined: d(180) },
  { id: 'user-004', name: 'Tóth Gábor', email: 'gabor.toth@ingatlas.hu', role: 'editor', avatar: 'TG', joined: d(120) },
  { id: 'user-005', name: 'Kiss Éva', email: 'eva.kiss@ingatlas.hu', role: 'viewer', avatar: 'KE', joined: d(60) },
]

const KPIS = {
  activeListings: 9,
  totalVisitors: 1847,
  chatbotQuestions: 561,
  conversionRate: 12.4,
  totalVisitorsThisWeek: 124,
  chatbotQuestionsToday: 48,
  avgViewTime: '4 perc 12 mp',
}

export {
  PROPERTIES,
  MONTHLY_VISITS,
  DAILY_VISITS,
  CHATBOT_QUESTIONS,
  CATEGORY_COUNTS,
  HEATMAP_DATA,
  SEO_TEXTS,
  TEAM_MEMBERS,
  KPIS,
}
